CarRepair/Models/Bus.cs
using CarRepair.Attributes;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace CarRepair.Models
{
    public class Bus : Car
    {
        [Display(Name = "Состояние поручней:")]
        [Range(0, 100)]
        public int GrabHandle { get; set; }

        [ServiceCost(300)]
        [Display(Name = "Сменить обивку сидений в салоне?")]
        public bool Lining { get; set; }
    }
}

CarRepair/Models/Car.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace CarRepair.Models
{
    public abstract class Car
    {
        public readonly int repairCostOfOneComponent = 10;

        [Display(Name = "Состояние кузова:")]
        [Range(0, 100)]
        public int Body { get; set; }

        [Display(Name = "Состояние колес:")]
        [Range(0, 100)]
        public int Wheels { get; set; }

        [Display(Name = "Состояние двигателя:")]
        [Range(0, 100)]
        public int Engine { get; set; }

        [Display(Name = "Состояние тормозной системы:")]
        [Range(0, 100)]
        public int Brake { get; set; }

        [Display(Name = "Состояние ходовой части:")]
        [Range(0, 100)]
        public int Undercarriage { get; set; }

        [Display(Name = "Состояние салона:")]
        [Range(0, 100)]
        public int Interior { get; set; }
    }
}

CarRepair/Models/Truck.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace CarRepair.Models
{
    public class Truck : Car
    {
        [Display(Name = "Состояние гидравлической системы:")]
        [Range(0, 100)]
        public int Hydraulic { get; set; }
    }
}

CarRepair/Models/Vehicle.cs
using CarRepair.Attributes;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace CarRepair.Models
{
    public class Vehicle : Car
    {
        [ServiceCost(100)]
        [Display(Name = "Провести балансировку колес ?")]
        public bool WheelsBalance { get; set; }
    }
}

CarRepair/Controllers/BaseController.cs
using CarRepair.Attributes;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Reflection;
using System.Web;
using System.Web.Mvc;
using CarRepair.Code;

namespace CarRepair.Controllers
{
    public class BaseController : Controller, IRepairCalculator
    {
        public int GetRepairCost<T>(T car)
        {
            int propertyValuesSum = 0;
            int intReturnPropertiesCount = 0;
            int additionalRepairCost = 0;

            foreach (var property in typeof(T).GetProperties())
            {
                PropertyInfo pi = typeof(T).GetProperty(property.Name);

                switch (property.PropertyType.Name)
                {
                    case "Int32":
                        intReturnPropertiesCount++;
                        propertyValuesSum += (int)pi.GetValue(car);
                        break;

                    case "Boolean":
                        if ((bool)pi.GetValue(car))
                        {
                            var attributeValue = pi.GetCustomAttribute(typeof(ServiceCostAttribute)) as ServiceCostAttribute;
                            additionalRepairCost += attributeValue.Cost;
                        }
                        break;
                    default:
                        throw new ArgumentException("Allows only Int32 and Bool properties");
                }
            }

            return (intReturnPropertiesCount * 100 - propertyValuesSum) * 10 + additionalRepairCost;
        }
        public int GetCarCondition<T>(T car)
        {
            int propertyValuesSum = 0;
            int intReturnPropertiesCount = 0;

            foreach (var property in typeof(T).GetProperties())
            {
                PropertyInfo pi = typeof(T).GetProperty(property.Name);

                switch (property.PropertyType.Name)
                {
                    case "Int32":
                        intReturnPropertiesCount++;
                        propertyValuesSum += (int)pi.GetValue(car);
                        break;

                    case "Boolean":
                        break;
                    default:
                        throw new ArgumentException("Allows only Int32 and Bool properties");
                }
            }

            return propertyValuesSum / intReturnPropertiesCount;
        }
    }
}

CarRepair/Controllers/BusController.cs
using CarRepair.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace CarRepair.Controllers
{
    public class BusController : BaseController
    {
        // GET: Bus
        public ActionResult Repair()
        {

            return PartialView("_BusRepair");
        }
        [HttpPost]
        public ActionResult Calculate(Bus bus)
        {
            //register in db..
            ViewBag.repairCost = GetRepairCost(bus);
            ViewBag.carCondition = GetCarCondition(bus);

            return View();
        }
    }
}

CarRepair/Controllers/HomeController.cs
using CarRepair.Attributes;
using CarRepair.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Reflection;
using System.Web;
using System.Web.Mvc;
using System.Web.Routing;

namespace CarRepair.Controllers
{
    public class HomeController : Controller 
    {
        // GET: Home
        public ActionResult Index()
        {

            return View();
    
        }
    }
}

CarRepair/Controllers/TruckController.cs
using CarRepair.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace CarRepair.Controllers
{
    public class TruckController : BaseController
    {
        // GET: Truck
        public ActionResult Repair()
        {

            return PartialView("_TruckRepair");
        }
        [HttpPost]
        public ActionResult Calculate(Truck truck)
        {
            ViewBag.repairCost = GetRepairCost(truck);
            ViewBag.carCondition = GetCarCondition(truck);

            return View();
        }
    }
}

CarRepair/Controllers/VehicleController.cs
using CarRepair.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace CarRepair.Controllers
{
    public class VehicleController : BaseController
    {
        // GET: Vehicle
        public ActionResult Repair()
        {

           return PartialView("_VehicleRepair");
        }
        [HttpPost]
        public ActionResult Calculate(Vehicle vehicle)
        {
            ViewBag.repairCost = GetRepairCost(vehicle);
            ViewBag.carCondition = GetCarCondition(vehicle);

            return View();
        }
    }
}

CarRepair/Views/Bus/_BusRepair.cshtml
@model CarRepair.Models.Bus

@using (Html.BeginForm("Calculate", "Bus", FormMethod.Post))
{
        <label>
            @Html.DisplayNameFor(m => m.Body)
        </label>

        @Html.TextBoxFor(m => m.Body, new { @type = "range", @min = "0", @max = "100", @Value = "100", @onchange = "document.getElementById('body').innerHTML = this.value;" })
        <span id="body">100</span>
        <br />

        <label>
            @Html.DisplayNameFor(m => m.Wheels)
        </label>

        @Html.TextBoxFor(m => m.Wheels, new { @type = "range", @min = "0", @max = "100", @Value = "100", @onchange = "document.getElementById('wheels').innerHTML = this.value;" })
        <span id="wheels">100</span>
        <br />

        <label>
            @Html.DisplayNameFor(m => m.Engine)
        </label>

        @Html.TextBoxFor(m => m.Engine, new { @type = "range", @min = "0", @max = "100", @Value = "100", @onchange = "document.getElementById('engine').innerHTML = this.value;" })
        <span id="engine">100</span>
        <br />

        <label>
            @Html.DisplayNameFor(m => m.Brake)
        </label>

        @Html.TextBoxFor(m => m.Brake, new { @type = "range", @min = "0", @max = "100", @Value = "100", @onchange = "document.getElementById('brake').innerHTML = this.value;" })
        <span id="brake">100</span>
        <br />

        <label>
            @Html.DisplayNameFor(m => m.Undercarriage)
        </label>

        @Html.TextBoxFor(m => m.Undercarriage, new { @type = "range", @min = "0", @max = "100", @Value = "100", @onchange = "document.getElementById('undercarriage').innerHTML = this.value;" })
        <span id="undercarriage">100</span>
        <br />

        <label>
            @Html.DisplayNameFor(m => m.Interior)
        </label>

        @Html.TextBoxFor(m => m.Interior, new { @type = "range", @min = "0", @max = "100", @Value = "100", @onchange = "document.getElementById('interior').innerHTML = this.value;" })
        <span id="interior">100</span>
        <br />

        <label>
            @Html.DisplayNameFor(m => m.GrabHandle)
        </label>

        @Html.TextBoxFor(m => m.GrabHandle, new { @type = "range", @min = "0", @max = "100", @Value = "100", @onchange = "document.getElementById('grabHandle').innerHTML = this.value;" })
        <span id="grabHandle">100</span>
        <br />

        <label>
            @Html.DisplayNameFor(m => m.Lining)
        </label>

        @Html.CheckBoxFor(m => m.Lining)

        <p><input type="submit" class="btn btn-default" value="Узнать стоимость ремонта" /></p>

}

CarRepair/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Index";
}
<br />
<p>Выберите тип вашей машины</p>
<div id="type">
    <label>
        <input type="radio" name="radio" onclick="$('#carCondition').load('@Url.Action("Repair", "Bus")')" />Автобус
    </label>
    <label>
        <input type="radio" name="radio" onclick="$('#carCondition').load('@Url.Action("Repair", "Truck")')" />Грузовик
    </label>
    <label>
        <input type="radio" name="radio" onclick="$('#carCondition').load('@Url.Action("Repair", "Vehicle")')" />Легковая
    </label>
</div>
<div id="carCondition">

</div>

CarRepair/Views/Shared/Calculate.cshtml
@{
    ViewBag.Title = "Result";
}
<br />
<p>Общее состояние машины: @ViewBag.carCondition % </p>
<p>К оплате @ViewBag.repairCost грн</p>

@Html.ActionLink("Рассчитать стоимость ремонта еще одной машины", "Index", "Home")

CarRepair/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.6.2.js"></script>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Car repair", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                </ul>
            </div>
        </div>
    </div>

    <div class="container body-content">
        @RenderBody()
    </div>

    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
</body>
</html>

CarRepair/Views/Truck/_TruckRepair.cshtml
@model CarRepair.Models.Truck

@using (Html.BeginForm("Calculate", "Truck", FormMethod.Post))
{
        <label>
            @Html.DisplayNameFor(m => m.Body)
        </label>

        @Html.TextBoxFor(m => m.Body, new { @type = "range", @min = "0", @max = "100", @Value = "100", @onchange = "document.getElementById('body').innerHTML = this.value;" })
        <span id="body">100</span>
        <br />

        <label>
            @Html.DisplayNameFor(m => m.Wheels)
        </label>

        @Html.TextBoxFor(m => m.Wheels, new { @type = "range", @min = "0", @max = "100", @Value = "100", @onchange = "document.getElementById('wheels').innerHTML = this.value;" })
        <span id="wheels">100</span>
        <br />

        <label>
            @Html.DisplayNameFor(m => m.Engine)
        </label>

        @Html.TextBoxFor(m => m.Engine, new { @type = "range", @min = "0", @max = "100", @Value = "100", @onchange = "document.getElementById('engine').innerHTML = this.value;" })
        <span id="engine">100</span>
        <br />

        <label>
            @Html.DisplayNameFor(m => m.Brake)
        </label>

        @Html.TextBoxFor(m => m.Brake, new { @type = "range", @min = "0", @max = "100", @Value = "100", @onchange = "document.getElementById('brake').innerHTML = this.value;" })
        <span id="brake">100</span>
        <br />

        <label>
            @Html.DisplayNameFor(m => m.Undercarriage)
        </label>

        @Html.TextBoxFor(m => m.Undercarriage, new { @type = "range", @min = "0", @max = "100", @Value = "100", @onchange = "document.getElementById('undercarriage').innerHTML = this.value;" })
        <span id="undercarriage">100</span>
        <br />

        <label>
            @Html.DisplayNameFor(m => m.Interior)
        </label>

        @Html.TextBoxFor(m => m.Interior, new { @type = "range", @min = "0", @max = "100", @Value = "100", @onchange = "document.getElementById('interior').innerHTML = this.value;" })
        <span id="interior">100</span>
        <br />

        <label>
            @Html.DisplayNameFor(m => m.Hydraulic)
        </label>

        @Html.TextBoxFor(m => m.Hydraulic, new { @type = "range", @min = "0", @max = "100", @Value = "100", @onchange = "document.getElementById('hydraulic').innerHTML = this.value;" })
        <span id="hydraulic">100</span>
        <br />

        <p><input type="submit" class="btn btn-default" value="Узнать стоимость ремонта" /></p>

}

CarRepair/Views/Vehicle/_VehicleRepair.cshtml
@model CarRepair.Models.Vehicle

@using (Html.BeginForm("Calculate", "Vehicle", FormMethod.Post))
{

        <label>
            @Html.DisplayNameFor(m => m.Body)
        </label>

        @Html.TextBoxFor(m => m.Body, new { @type = "range", @min = "0", @max = "100", @Value = "100", @onchange = "document.getElementById('body').innerHTML = this.value;" })
        <span id="body">100</span>
        <br />
        

        <label>
            @Html.DisplayNameFor(m => m.Wheels)
        </label>

        @Html.TextBoxFor(m => m.Wheels, new { @type = "range", @min = "0", @max = "100", @Value = "100", @onchange = "document.getElementById('wheels').innerHTML = this.value;" })
        <span id="wheels">100</span>
        <br />

        <label>
            @Html.DisplayNameFor(m => m.Engine)
        </label>

        @Html.TextBoxFor(m => m.Engine, new { @type = "range", @min = "0", @max = "100", @Value = "100", @onchange = "document.getElementById('engine').innerHTML = this.value;" })
        <span id="engine">100</span>
        <br />

        <label>
            @Html.DisplayNameFor(m => m.Brake)
        </label>

        @Html.TextBoxFor(m => m.Brake, new { @type = "range", @min = "0", @max = "100", @Value = "100", @onchange = "document.getElementById('brake').innerHTML = this.value;" })
        <span id="brake">100</span>
        <br />

        <label>
            @Html.DisplayNameFor(m => m.Undercarriage)
        </label>

        @Html.TextBoxFor(m => m.Undercarriage, new { @type = "range", @min = "0", @max = "100", @Value = "100", @onchange = "document.getElementById('undercarriage').innerHTML = this.value;" })
        <span id="undercarriage">100</span>
        <br />

        <label>
            @Html.DisplayNameFor(m => m.Interior)
        </label>

        @Html.TextBoxFor(m => m.Interior, new { @type = "range", @min = "0", @max = "100", @Value = "100", @onchange = "document.getElementById('interior').innerHTML = this.value;" })
        <span id="interior">100</span>
        <br />

        <label>
            @Html.DisplayNameFor(m => m.WheelsBalance)
        </label>
        @Html.CheckBoxFor(m => m.WheelsBalance)

        <p><input type="submit" class="btn btn-default" value="Узнать стоимость ремонта" /></p>

}